-- DoKi database schema for Supabase PostgreSQL.
-- Run this script in Supabase Dashboard -> SQL Editor.

create table if not exists public.users (
    id integer generated by default as identity primary key,
    full_name varchar not null,
    business_name varchar not null,
    email varchar not null unique,
    phone varchar not null unique,
    password_hash varchar not null,
    role varchar not null check (role in ('SELLER', 'BUYER')),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create table if not exists public.waste_listings (
    id integer generated by default as identity primary key,
    title varchar(255) not null,
    description text,
    category varchar not null check (
        category in (
            'food_processing',
            'brewery_spent_grain',
            'coffee_hulls_pulp',
            'market_organic_waste',
            'dairy_sugar_byproducts',
            'animal_manure',
            'other_organic'
        )
    ),
    quantity_tonnes double precision not null check (quantity_tonnes >= 0),
    price_per_unit double precision not null check (price_per_unit >= 0),
    unit varchar(50) not null default 'tonne',
    moisture_content varchar(100),
    purity_level varchar(100),
    quality_grade varchar(100),
    location varchar(255) not null,
    image_url varchar(500),
    status varchar not null default 'active' check (
        status in ('pending', 'active', 'flagged', 'sold', 'rejected')
    ),
    seller_id integer not null references public.users(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.classifications (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id),
    image_url varchar not null,
    waste_type varchar not null,
    confidence varchar not null,
    description text not null,
    possible_uses jsonb not null,
    status varchar not null default 'pending_review',
    created_at timestamptz not null default now()
);

create table if not exists public.listing_moderation_logs (
    id integer generated by default as identity primary key,
    listing_id integer not null references public.waste_listings(id),
    admin_id integer not null references public.users(id),
    action varchar(50) not null,
    reason text,
    created_at timestamptz not null default now()
);

create table if not exists public.business_verification_requests (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id),
    business_name varchar(255) not null,
    registration_number varchar(100) not null,
    document_url varchar(500),
    status varchar(50) not null default 'pending' check (
        status in ('pending', 'approved', 'rejected')
    ),
    reviewed_at timestamptz
);

create table if not exists public.disputes (
    id integer generated by default as identity primary key,
    reporter_id integer not null references public.users(id),
    listing_id integer not null references public.waste_listings(id),
    reason varchar(255) not null,
    details text,
    status varchar(50) not null default 'open' check (
        status in ('open', 'under_review', 'resolved', 'dismissed')
    ),
    created_at timestamptz not null default now()
);

create index if not exists ix_users_email
    on public.users(email);

create index if not exists ix_users_phone
    on public.users(phone);

create index if not exists ix_waste_listings_seller_id
    on public.waste_listings(seller_id);

create index if not exists ix_waste_listings_status
    on public.waste_listings(status);

create index if not exists ix_waste_listings_category
    on public.waste_listings(category);

create index if not exists ix_classifications_user_id
    on public.classifications(user_id);

create index if not exists ix_listing_moderation_logs_listing_id
    on public.listing_moderation_logs(listing_id);

create index if not exists ix_listing_moderation_logs_admin_id
    on public.listing_moderation_logs(admin_id);

create index if not exists ix_business_verification_requests_user_id
    on public.business_verification_requests(user_id);

create index if not exists ix_disputes_reporter_id
    on public.disputes(reporter_id);

create index if not exists ix_disputes_listing_id
    on public.disputes(listing_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_waste_listings_updated_at
    on public.waste_listings;

create trigger set_waste_listings_updated_at
before update on public.waste_listings
for each row execute function public.set_updated_at();

-- Row-level security
--
-- The current API uses custom JWTs rather than Supabase Auth, so auth.uid()
-- cannot identify rows in these tables. Browser roles are therefore denied
-- until the API is migrated to Supabase Auth or carefully scoped RPC policies.
-- The backend service-role key bypasses RLS and remains able to access data.

alter table public.users enable row level security;
alter table public.waste_listings enable row level security;
alter table public.classifications enable row level security;
alter table public.listing_moderation_logs enable row level security;
alter table public.business_verification_requests enable row level security;
alter table public.disputes enable row level security;

drop policy if exists "deny anon users" on public.users;
create policy "deny anon users"
on public.users for all to anon
using (false) with check (false);

drop policy if exists "deny authenticated users" on public.users;
create policy "deny authenticated users"
on public.users for all to authenticated
using (false) with check (false);

drop policy if exists "deny anon users" on public.waste_listings;
create policy "deny anon users"
on public.waste_listings for all to anon
using (false) with check (false);

drop policy if exists "deny authenticated users" on public.waste_listings;
create policy "deny authenticated users"
on public.waste_listings for all to authenticated
using (false) with check (false);

drop policy if exists "deny anon users" on public.classifications;
create policy "deny anon users"
on public.classifications for all to anon
using (false) with check (false);

drop policy if exists "deny authenticated users" on public.classifications;
create policy "deny authenticated users"
on public.classifications for all to authenticated
using (false) with check (false);

drop policy if exists "deny anon users" on public.listing_moderation_logs;
create policy "deny anon users"
on public.listing_moderation_logs for all to anon
using (false) with check (false);

drop policy if exists "deny authenticated users" on public.listing_moderation_logs;
create policy "deny authenticated users"
on public.listing_moderation_logs for all to authenticated
using (false) with check (false);

drop policy if exists "deny anon users" on public.business_verification_requests;
create policy "deny anon users"
on public.business_verification_requests for all to anon
using (false) with check (false);

drop policy if exists "deny authenticated users" on public.business_verification_requests;
create policy "deny authenticated users"
on public.business_verification_requests for all to authenticated
using (false) with check (false);

drop policy if exists "deny anon users" on public.disputes;
create policy "deny anon users"
on public.disputes for all to anon
using (false) with check (false);

drop policy if exists "deny authenticated users" on public.disputes;
create policy "deny authenticated users"
on public.disputes for all to authenticated
using (false) with check (false);
